name: animatediff_xl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - numpy=1.25.0
  - pillow=9.4.0
  - python=3.10.12
  - pytorch-cuda=11.7
  - pip
  - pip:
      - absl-py==1.4.0
      - accelerate==0.21.0
      - av==10.0.0
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.41.1
      - colorama==0.4.4
      - decord==0.6.0
      - diffusers==0.20.2
      - easydict==1.10
      - einops==0.7.0rc1
      - gdown==4.7.1
      - imageio==2.27.0
      - omegaconf==2.3.0
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.65.0
      - transformers==4.30.0
      - wandb==0.15.8
      - xformers==0.0.22.post4
      - scipy
      - imageio[ffmpeg]
